default: &default
  appid: "wx09a1b0c63b622b67"
  secret: "67fc4662f5471b1c8e74ab7e084029e4"
  token:  "weixin"
  access_token: "/var/tmp/wechatr_wechat_access_token"

production: 
  appid: <%= ENV['WECHAT_APPID'] %>
  secret: <%= ENV['WECHAT_APP_SECRET'] %>
  token:   <%= ENV['WECHAT_TOKEN'] %>
  access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>

staging: 
  <<: *default

development: 
  <<: *default

test: 
  <<: *default